### ISSUE TITLE
.set

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [nuelsoft/coinhaven_test#5]
https://github.com/nuelsoft/coinhaven_test/blob/e87b7daa5df0749120644ed6b7c67f21733b5288/src/services/store/store.js#L100

so, you decided to use simple key to store user data in? :)

**Comment by nuelsoft** [comment]
Hi @Dmitry-N-Medvedev, I am done with task. I hope you get a chance to look at this today.

Looking forward to hearing from you ✌️
